
backend:
  name: github
  repo: <ORG>/<REPO>
  branch: main
media_folder: "public/images/blog"
public_folder: "/images/blog"
collections:
  - name: posts
    label: Articles
    folder: blog
    create: true
    format: frontmatter
    slug: "{{slug}}"
    identifier_field: title
    preview_path: "/blog/{{slug}}"
    fields:
      - {label: Titre, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: text}
      - {label: Image, name: image, widget: image}
      - {label: Corps,  name: body, widget: markdown}
